<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'cli' => array($vendorDir . '/wp-cli/php-cli-tools/lib'),
    'WP_CLI' => array($vendorDir . '/wp-cli/wp-cli/php'),
    'Symfony\\Component\\Yaml\\' => array($vendorDir . '/symfony/yaml'),
    'Symfony\\Component\\VarDumper\\' => array($vendorDir . '/symfony/var-dumper'),
    'Symfony\\Component\\Templating\\' => array($vendorDir . '/symfony/templating'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'Requests' => array($vendorDir . '/rmccue/requests/library'),
    'ParaTest' => array($vendorDir . '/brianium/paratest/src', $vendorDir . '/brianium/paratest/test', $vendorDir . '/brianium/paratest/it'),
    'Oxymel' => array($vendorDir . '/nb/oxymel'),
    'Mustache' => array($vendorDir . '/mustache/mustache/src'),
    'Joomlatools\\' => array($vendorDir . '/joomlatools/joomla-console/src'),
    'Habitat' => array($vendorDir . '/brianium/habitat/src'),
    'GitScan\\' => array($vendorDir . '/totten/git-scan/src'),
    'Drush' => array($vendorDir . '/drush/drush/lib'),
    'DB\\' => array($vendorDir . '/totten/amp/src'),
    'Boris' => array($vendorDir . '/d11wtq/boris/lib'),
    'Amp\\' => array($vendorDir . '/totten/amp/src'),
);
